### ISSUE TITLE
Receiving the following Error "name 'hashes' is not defined"

### ISSUE THREAD

**Issue by OoShinkooO** [hegusung/WebHashcat#11]
http://dpaste.com/3EC6705

Environment:

Request Method: POST
Request URL: http://192.168.2.201/new_session

Django Version: 2.0.7
Python Version: 3.5.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'Nodes',
 'Hashcat',
 'Utils',
 'API',
 'Auth']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/usr/local/share/WebHashcat/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/usr/local/share/WebHashcat/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/share/WebHashcat/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/share/WebHashcat/lib/python3.5/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/opt/WebHashcat/Hashcat/views.py" in new_session
  177.             res = hashcat_api.create_mask_session(session_name, hashfile, mask)

File "/opt/WebHashcat/Utils/hashcatAPI.py" in create_mask_session
  67.                 "hashes": hashes,

Exception Type: NameError at /new_session
Exception Value: name 'hashes' is not defined

**Comment by OoShinkooO** [comment]
[FireShot Capture 008 - NameError at _new_session - http___192.168.2.201_new_session.pdf](https://github.com/hegusung/WebHashcat/files/2259616/FireShot.Capture.008.-.NameError.at._new_session.-.http___192.168.2.201_new_session.pdf)

In the mean time, I've disabled the line  ""hashes": hashes," as it appears there is no definition of the variable hashes.  Based on the description, it appears to be related "Atomicity".
 
/WebHashcat/Utils/hashcatAPI.py

--- Initial Configuration----
def create_mask_session(self, session_name, hashfile, mask):
        hashfile_path = os.path.join(os.path.dirname(__file__), "..", "Files", "Hashfiles", hashfile.hashfile)

        from Utils.hashcat import Hashcat
        from Hashcat.models import Hashfile

        # lock
        with transaction.atomic():
            # Prevent hashfile from being modified while read
            hashfile_lock = Lock.objects.select_for_update().filter(hashfile_id=hashfile.id, lock_ressource="hashfile")[0]


            payload = {
                "name": session_name,
                "crack_type": "mask",
                "hash_mode_id": hashfile.hash_type,
                "mask": mask,
                "hashes": hashes,
                "username_included": False,
            }

            res = self.post_file("/createSession", payload, hashfile_path)

            del hashfile_lock

        return res

--- Changes Made------
def create_mask_session(self, session_name, hashfile, mask):
        hashfile_path = os.path.join(os.path.dirname(__file__), "..", "Files", "Hashfiles", hashfile.hashfile)

        from Utils.hashcat import Hashcat
        from Hashcat.models import Hashfile

        # lock
        with transaction.atomic():
            # Prevent hashfile from being modified while read
            hashfile_lock = Lock.objects.select_for_update().filter(hashfile_id=hashfile.id, lock_ressource="hashfile")[0]


            payload = {
                "name": session_name,
                "crack_type": "mask",
                "hash_mode_id": hashfile.hash_type,
                "mask": mask,
                #"hashes": hashes,
                "username_included": False,
            }

            res = self.post_file("/createSession", payload, hashfile_path)

            del hashfile_lock

        return res

**Comment by hegusung** [comment]
Hi,

Thanks for reporting this issue. Should be fine now.
