### ISSUE TITLE
KeyError:Hashcat

### ISSUE THREAD

**Issue by loop786** [hegusung/WebHashcat#19]
Request Method: | GET
-- | --
http://127.0.0.1:8000/hashfiles
2.2.1
KeyError
'Hashcat'
/usr/lib/python3.6/configparser.py in __getitem__, line 959
/usr/bin/python3
3.6.7
['/Hashcat/WebHashcat/WebHashcat',  '/Hashcat/WebHashcat/WebHashcat',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Wed, 29 May 2019 06:52:10 +0000

**Comment by hegusung** [comment]
It seems like there is an issue in your configuration file, could you post it (Webhashcat/settings.ini)
