### ISSUE TITLE
Incomplete installation instruction.

### ISSUE THREAD

**Issue by Torxed** [hegusung/WebHashcat#22]
Wasn't able to follow the instructions at all.
One thing that made it clear that it's out of date was `settings.py` doesn't exist. 

https://github.com/hegusung/WebHashcat/search?q=settings.py&unscoped_q=settings.py

Most likely because `.gitignore` contains `WebHashcat/WebHashcat/settings.py`.

**Comment by hegusung** [comment]
I usually create a *.sample of the config files.
I updated the README to explain this, thank you for the report.
