### ISSUE TITLE
Rules/Masks/Wordlists empty

### ISSUE THREAD

**Issue by tautology0** [hegusung/WebHashcat#31]
This is a weird one: when I try adding my local hashcatnode, it will successfully enumerate the hash types and reflect this in the front end, but rules, masks and wordlists are empty.

Adding debugging print statements to hashcatnode show that it is passing it to webhashcat in the JSON, but they remain empty when I try to add a cracking job or view the node.

**Comment by hegusung** [comment]
Did you synchronize the node ? For the moment when a new file is added using the front end, it is not sent to the nodes.
