### ISSUE TITLE
GPG error when trying to build hashcatnode with docker_compose.yml

### ISSUE THREAD

**Issue by squeeze-the-box** [hegusung/WebHashcat#35]
It looks like its having an issue with the Nvidia CUDA drivers

------
 > [ 2/16] RUN apt-get update && apt-get install -y     python3     python3-pip:
#0 0.718 Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
#0 0.718 Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
#0 0.769 Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease [1581 B]
#0 0.807 Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
#0 0.835 Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
#0 0.905 Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
#0 0.912 Err:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
#0 0.912   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#0 0.923 Hit:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
#0 1.035 Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [29.8 kB]
#0 1.073 Get:9 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2284 kB]
#0 1.416 Get:11 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [957 kB]
#0 1.968 Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3231 kB]
#0 2.856 Get:13 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2798 kB]
#0 3.292 Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [991 kB]
#0 3.727 Get:15 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [12.2 kB]
#0 3.732 Get:16 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [12.9 kB]
#0 6.752 Get:17 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1512 kB]
#0 8.824 Get:18 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [22.8 kB]
#0 9.036 Reading package lists...
#0 11.03 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#0 11.03 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is no longer signed.
------
failed to solve: executor failed running [/bin/sh -c apt-get update && apt-get install -y     python3     python3-pip]: exit code: 100

**Comment by hegusung** [comment]
Docker-composed has been reworked
