### ISSUE TITLE
Exception Value: division by zero

### ISSUE THREAD

**Issue by cybergh00st** [hegusung/WebHashcat#9]
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/hashfile/10

Django Version: 2.0.6
Python Version: 3.5.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'Nodes',
 'Hashcat',
 'Utils',
 'API',
 'Auth']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/home/hidden/.local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/home/hidden/.local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/home/hidden/.local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/hidden/.local/lib/python3.5/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/hidden/WebHashcat/WebHashcat/Hashcat/views.py" in hashfile
  247.     context['recovered'] = "%s (%.2f%%)" % (humanize.intcomma(hashfile.cracked_count), hashfile.cracked_count/hashfile.line_count*100)

Exception Type: ZeroDivisionError at /hashfile/10
Exception Value: division by zero

**Comment by hegusung** [comment]
Hello,
Thanks for your issue and sorry for the delay, this bug should not appear anymore.
